/* Generated by CodeDescriptor 1.5.0.0907 */
/*
* Project Name      -> Ring Puffer
* Version           -> 1.0.0.0809
* Author            -> Jan @ Workstadion.: LAPTOP-DS345B1K
* Build Date        -> 09.08.2018 19:48:11
* Description       -> Ring Puffer 
*
*
*
*/

#ifndef __RINGBUFF_H__
#define __RINGBUFF_H__

#include <stdint.h>
#include <stdbool.h>

#define RBUFsize		50

/*	Ringpuffer Struktur
*/
typedef struct
{
	uint8_t		in;  			/**< Current storage location in the circular buffer. */
	uint8_t		out;  			/**< Current retrieval location in the circular buffer. */
	uint16_t	size;  			/**< size of the buffer's underlying storage array. */
	uint16_t	count;  		/**< Number of bytes currently stored in the buffer. */
	char 		buff[RBUFsize];
	
}ringBuffer_t;
ringBuffer_t ringBuffer;



void 		ringBufferInit				( void );

uint16_t 	ringBufferGetCount			( void );

uint16_t 	ringBufferGetFreeCount		( void );

bool 		ringBufferIsEmpty			( void );

bool 		ringBufferIsFull			( void );

void 		ringBufferInsert			( char data );

char 		ringBufferGet				( void );

uint8_t 	ringBufferPeek				( void );

#endif
