/* Generated by CodeDescriptor 1.5.0.0907 */
/*
* Project Name      -> Ringspeicher
* Version           -> 1.0.0.1211
* Author            -> Hm @ Workstadion.: QP-01-02
* Build Date        -> 11.12.2018 13:00:27
* Description       -> Description
*
*
*
*/

#ifndef __RINGBUFFER_H__
#define __RINGBUFFER_H__

#define RINGBUFFER_DEBUG_ENABLE

#include <stdint.h>



typedef struct
{
	uint8_t *Buffer;
	
	uint8_t BufferSize;
	
	uint8_t ReadPos;
	uint8_t WritePos;
	
	bool IsFull;

}RingBuff_t;



static void	RingBufferAdd( RingBuff_t *RingBuff , uint8_t *Data , uint8_t Offset , uint8_t Length );

RingBuff_t	RingBufferCreate( uint8_t Capacity );

void		RingBufferDestroy( RingBuff_t *RingBuff );

uint8_t		RingBufferGetLength( RingBuff_t *RingBuff );

void		RingBufferClear( RingBuff_t *RingBuff );

uint8_t		RingBufferPush( RingBuff_t *RingBuff , uint8_t *Data , uint8_t Length );

uint8_t		RingBufferPull( RingBuff_t *RingBuffer , uint8_t *Buff , uint8_t Length );

#endif
