/* Generated by CodeDescriptor 1.5.0.0907 */
/*
* Project Name      -> ATxmega Init.
* Version           -> 1.0.0.0719
* Author            -> Hm @ Workstadion.: QP-01-02
* Build Date        -> 19.07.2018 06:33:13
* Description       -> Description
*
*
*	ATXMEGA Initalisieren
*/




/* xmega32MhzInit
* @para             -> -none
* @return           -> -none
* @description      -> Initalisiert den 32MHz Oszillator
*/
void		xmega32MhzInit(void);

/* xmega32MhzInit
* @para             -> -none
* @return           -> -none
* @description      -> Initalisiert den 32KHz Oszillator
*/
void		xmega32KhzInit(void);
