/* Generated by CodeDescriptor 1.5.0.0907 */
/*
* Project Name      -> ATxmega Konfiguration
* Version           -> 1.0.0.0719
* Author            -> Hm @ Workstadion.: QP-01-02
* Build Date        -> 19.07.2018 06:33:13
* Description       -> Description
*
*
*	ATXMEGA Konfiguration
*/


#ifndef __ATXMEGA_INIT_H__
#define __ATXMEGA_INIT_H__

#ifdef __AVR__

	#include "../Headers/wsq3000_def.h"
	#include <avr/io.h>

#endif


void		xmega32MhzInit( void )	
{
	CCP			= CCP_IOREG_gc;                    // allow changing CLK.CTRL
	OSC.CTRL	= OSC_RC32MEN_bm;                  // enabling the 32MHz RC oscillator
	while ( ! ( OSC.STATUS & OSC_RC32MRDY_bm ) );  // wait for ready
	CCP			= CCP_IOREG_gc;                    // allow changing CLK.CTRL
	CLK.CTRL	= CLK_SCLKSEL_RC32M_gc ;           // system clock is internal 32MHz RC
}

void		xmega32KhzInit( void )	
{
	CCP			= CCP_IOREG_gc;						// allow changing CLK.CTRL
	OSC.CTRL	= OSC_RC32KEN_bm;					// enabling the 32kHz RC oscillator
	while ( ! ( OSC.STATUS & OSC_RC32KRDY_bm ) );	// wait for ready
	CCP			= CCP_IOREG_gc;                     // allow changing CLK.CTRL
	CLK.CTRL	= CLK_SCLKSEL_RC32K_gc ;			// system clock is internal 32kHz RC
}

#endif 