/* Generated by CodeDescriptor 1.5.0.0907 */
/*
* Project Name      -> Build Infos
* Version           -> 1.0.0.1231
* Author            -> Jan Homann @ Workstadion.: XXXJANIIIX3XXX
* Build Date        -> 31.12.2017 11:19:49
* Description       -> Building infos from Preprocessor
*
*
*
*/

#include <avr/io.h>

#include "version_num.h"
#include "build_info.h"


char *buildVer(void)
{
	static char build[19] = "0000000000000000000";
	
	/*
	*	major and minor version
	*/
	build[0] = verMajor;
	build[1] = '.';
	build[2] = verMinor;
	build[3] = '.';
	
	/*
	*	Fehlerkorrekturen
	*/
	build[4] = ( ( FEHLERKORREKTUR / 10000 )	% 10 )	+ '0';
	build[5] = ( ( FEHLERKORREKTUR / 1000 )		% 10 )	+ '0';
	build[6] = ( ( FEHLERKORREKTUR / 100 )		% 10 )	+ '0';
	build[7] = ( ( FEHLERKORREKTUR / 10 )		% 10 )	+ '0';
	build[8] = (   FEHLERKORREKTUR % 10 )				+ '0';
	build[9] = '.';
	
	/*
	*	time.: hour|min
	*/
	build[10] = __TIME__[0];
	build[11] = __TIME__[1];
	build[12] = __TIME__[3];
	build[13] = __TIME__[4];
	
	build[14] = '.';
	
	/*
	*	day
	*/
	build[15] = ((__DATE__[4] >= '0') ? (__DATE__[4]) : '0');
	build[16] = (__DATE__[ 5]);
	
	/*
	*	month
	*/
	if(__DATE__[0] == 'J' && __DATE__[1] == 'a')
	build[17] = '1'; // Januar

	if(__DATE__[0] == 'F')
	build[17] = '2'; // Februar
	
	if(__DATE__[0] == 'M' && __DATE__[1] == 'a' && __DATE__[2] == 'r')
	build[17] = '3'; // März
	
	if(__DATE__[0] == 'A' && __DATE__[1] == 'p')
	build[17] = '4'; // April
	
	if(__DATE__[0] == 'M' && __DATE__[1] == 'a' && __DATE__[2] == 'y')
	build[17] = '5'; // Mai
	
	if(__DATE__[0] == 'J' && __DATE__[1] == 'u' && __DATE__[2] == 'n')
	build[17] = '6'; // Juni
	
	if(__DATE__[0] == 'J' && __DATE__[1] == 'u' && __DATE__[2] == 'l')
	build[17] = '7'; // Juli
	
	if(__DATE__[0] == 'A' && __DATE__[1] == 'u')
	build[17] = '8'; // August
	
	if(__DATE__[0] == 'S')
	build[17] = '9'; // September

	if(__DATE__[0] == 'O'){
		build[16] = '1';
		build[17] = '0'; // Oktober
	}

	if(__DATE__[0] == 'N'){
		build[16] = '1';
		build[17] = '1'; // November
	}
	
	if(__DATE__[0] == 'D'){
		build[16] = '1';
		build[17] = '2'; // Dezember
	}

	build[18] = '\0';
	
	return build;
}
