/* Generated by CodeDescriptor 1.5.0.0907 */
/*
* Project Name      -> Build Infos
* Version           -> 1.0.0.1231
* Author            -> Jan Homann @ Workstadion.: XXXJANIIIX3XXX
* Build Date        -> 31.12.2017 11:19:49
* Description       -> Building infos from Preprocessor
*
*
*
*/

#ifndef _WIN64
#include <avr/io.h>
#endif 

#include "version_num.h"
#include "build_info.h"


typedef struct
{
	char	Number[2];
	char 	Name[3];
}MonthTab_t;



char *BuildVersion(void)
{
	static char Version[10];

	const MonthTab_t Month[] = 
	{
		{ "01" , "Jan" },
		{ "02" , "Feb" },
		{ "03" , "Mrz" },
		{ "04" , "Apr" },
		{ "05" , "Mai" },
		{ "06" , "Jun" },
		{ "07" , "Jul" },
		{ "08" , "Aug" },
		{ "09" , "Sep" },
		{ "10" , "Okt" },
		{ "11" , "Nov" },
		{ "12" , "Dez" },
	};
	
	/*
	*	Major & Minor V
	*/
	Version[0] = VersionMajor;
	Version[1] = '.';
	Version[2] = VersionMinor;
	Version[3] = '.';
	
	/*
	*	Erstellungs Tag
	*/
	Version[4] = ((__DATE__[4] >= '0') ? (__DATE__[4]) : '0');
	Version[5] = (__DATE__[5]);
	Version[6] = '.';
	
	/*
	*	Erstellungs Monat
	*/
	for( uint8_t ui = 0 ; ui < 12 ; ui++ )
	{
		if( ( __DATE__[0] == Month[ui].Name[0] ) && ( __DATE__[1] == Month[ui].Name[1] ) && ( __DATE__[2] == Month[ui].Name[2] ) )
		{
			Version[7] = Month[ui].Number[0]; // Zehner
			Version[8] = Month[ui].Number[1]; // Einer
			
			break;
		}
	}

	Version[9] = '\0';
	
	return Version;
}

