/* Generated by CodeDescriptor 1.2.0.0713 */
/*
* Project Name      -> RX8564
* Version           -> 1.0.0.0714
* Author            -> Hm @ Workstadion.: QP-01-02
* Build Date        -> 14.07.2017 07:18:15
* Description       -> Device Driver
*
*
*
*/
#ifndef __RX8564_H__
#define __RX8564_H__

#include <stdint.h>

#ifdef __AVR__
	#include <avr/io.h>
	#include <avr/interrupt.h>	
	#include "i2cmaster.h"
#endif

//#define _WITH_ERROR_REPORT_

#ifdef _WITH_ERROR_REPORT_
	#include "../error.h"
#endif



/* Slave Address */
#define RX8564_ADDR 0xA2 

/* rtcSetClkOut Frequency */
#define F_32768Hz 0x80
#define F_1024Hz  0x81
#define F_32Hz	  0x82
#define F_1Hz	  0x83
#define F_STOP	  0x00


/* register addresses */
enum rx8564_register
{
	RX8564_CONTROL_1,
	RX8564_CONTROL_2,
	RX8564_SECONDS,
	RX8564_MINUTES,
	RX8564_HOURS,
	RX8564_DAYS,
	RX8564_DAY_NAME,
	RX8564_MONTH,
	RX8564_YEAR,
	RX8564_MINUTE_ALERT,
	RX8564_HOUR_ALERT,
	RX8564_DAY_ALERT,
	RX8564_DAY_NAME_ALERT,
	RX8564_CLKOUT_FREQUENCY,
	RX8564_TIMER_CONTROL,
	RX8564_TIMER,	
}rx8564_regs_enum;



 typedef struct
 {
	 uint8_t	second;
	 uint8_t	minute;
	 uint8_t	hour;
	 uint8_t	month;
	 uint8_t	day;
	 uint8_t	dayName;
	 uint16_t	year;
	 
	 uint8_t	alrt_minute;
	 uint8_t	alrt_hour;
	 uint8_t	alrt_day;
	 uint8_t	alrt_dayName;
	 
 }rx8564_t;



uint8_t					rtcBcdToDec				( uint8_t val );

uint8_t					rtcDecToBcd				( uint8_t val );


void					rtcInit					( void );

void					rtcSetTime				( uint8_t hour , uint8_t minutes , uint8_t seconds );

void					rtcSetDate				( uint8_t day , uint8_t weekDay , uint8_t month, uint16_t year );

void					rtcSetAlert				( uint8_t day , uint8_t weekDay , uint8_t hour, uint8_t minutes );

void					rtcSetClkOut			( uint8_t frequency );

void					rtcGetData				( rx8564_t *buffer );

void					rtcSetCtrl2				( uint8_t mask );

void					rtcSetTimerControl		( uint8_t mask );

uint8_t					rtcReadTimer			( void );

bool					rtcIsLeapYear			( const uint16_t year );

uint16_t				rtcGetNumOfDaysAtMonth	( const uint8_t month , const uint16_t year );

uint16_t				rtcGetDays				( const uint16_t year );

uint16_t				rtcGetWeekDay			( const uint8_t day , const uint8_t month , const uint16_t year );

uint16_t				rtcGetDayofYear			( const uint8_t day , const uint8_t month , const uint16_t year );

uint16_t				rtcGetWeek				( uint16_t day , uint16_t month , uint16_t year );


#endif //__RX8564_H__ 
