/* Generated by CodeDescriptor 1.2.0.0713 */
/*
* Project Name      -> RX8564
* Version           -> 1.0.0.0714
* Author            -> Hm @ Workstadion.: QP-01-02
* Build Date        -> 14.07.2017 07:18:15
* Description       -> Device Driver
*
*
*
*/


#include <avr/interrupt.h>
#include "rx8564.h"
#include "I2C.h"
#include "../error.h"
 
 static uint8_t buff[11] = "";

inline uint8_t bcdToDec(uint8_t val)
{
	return ((( val & 0xF0 ) >> 4 ) * 10 ) + ( val & 0x0F );
}

inline uint8_t decToBcd(uint8_t val)
{	
	return ((( val / 10 ) << 4) | ( val % 10 ));
}

uint8_t rx8564Reads( uint8_t *buff , uint8_t leng )
{
	if( i2c_start( RX8564_ADDR + I2C_WRITE ) )
	{
		errorWriteCircular( &err , _ERROR_RTC_I2C_ , ERROR_I2C_NO_ACK );
	}
	
	if ( i2c_write( buff[0] ) )// Register Adresse
	{
		errorWriteCircular( &err , _ERROR_RTC_I2C_ , ERROR_I2C_ADDRESS_TX );
	}
	
	if ( i2c_rep_start( RX8564_ADDR + I2C_READ ) )
	{
		errorWriteCircular( &err , _ERROR_RTC_I2C_ , ERROR_I2C_NO_ACK );
		i2c_stop();
		return 1;
	}
	
	for ( uint8_t i = 0 ; i < leng ; i++ )
	{
		if ( leng == 1 )
		{
			*buff = i2c_readNak();
			return 0;
		}
		else
		{
			*buff++ = i2c_readAck();
		}
	}
	*buff = i2c_readNak();
	i2c_stop();
	
	return 0;
}

uint8_t rx8564Writes( uint8_t *buff , uint8_t leng )
{
	i2c_start_wait( RX8564_ADDR + I2C_WRITE );

	for ( uint8_t i = 0 ; i < leng ; i++ )
	{
		if ( leng == 1 )
		{
			if ( i2c_write( *buff ) )
			{
				errorWriteCircular( &err , _ERROR_RTC_I2C_ , ERROR_I2C_BYTE_TX );	
			}
			
			i2c_stop();
			return 0;
		}
		else
		{
			if ( i2c_write( *buff++ ) )
			{
				errorWriteCircular( &err , _ERROR_RTC_I2C_ , ERROR_I2C_BYTE_TX );
			}
		}
	}
	i2c_stop();
	
	return 0;
}



void rtcInit(void)
{
	buff[0] = control_1_register;
	buff[1] = 0x00;
	rx8564Writes( buff , sizeof(buff) );
}

void rtcSetTime(uint8_t hour, uint8_t minutes, uint8_t seconds)
{
	buff[0] = seconds_register;
	buff[1] = decToBcd(seconds);
	buff[2] = decToBcd(minutes);
	buff[3] = decToBcd(hour);
	rx8564Writes( buff , sizeof(buff) );
} 
   
void rtcSetDate(uint8_t day, uint8_t week_day, uint8_t month, uint16_t year)
{
	buff[0] = day_register;
	buff[1] = decToBcd(day);
	buff[2] = decToBcd(week_day);
	buff[3] = decToBcd(month);
	buff[4] = decToBcd( year - 2000 );
	rx8564Writes( buff , sizeof(buff) );    
}
  
void rtcSetAlrt(uint8_t day, uint8_t week_day, uint8_t hour, uint8_t minutes)
{
	buff[0] = minute_alert_register;
	buff[1] = decToBcd(minutes);
	buff[2] = decToBcd(hour);
	buff[3] = decToBcd(day);
	buff[4] = decToBcd(week_day);
	rx8564Writes( buff , sizeof(buff) );
 }
  
void rtcSetClkOut(uint8_t frequency)
{    
	buff[0] = clkout_frequency_register;
	buff[1] = frequency;
	rx8564Writes( buff , sizeof(buff) );	
}
 
void rtcGetData(rx8564_t *buffer)
{   
	buff[0] = seconds_register;
	rx8564Reads( buff , sizeof(buff) );
			
    buffer->second			= buff[0];
    buffer->minute			= buff[1];  
    buffer->hour			= buff[2];
    buffer->day				= buff[3];
    buffer->dayName			= buff[4];
    buffer->month			= buff[5];
    buffer->year			= buff[6];
    buffer->alrt_minute		= buff[7];
    buffer->alrt_hour		= buff[8];
    buffer->alrt_day		= buff[9];
    buffer->alrt_dayName	= buff[10];

 
    buffer->second			&= 0x7F;
    buffer->minute			&= 0x7F;
    buffer->hour			&= 0x3F;
          
    buffer->day				&= 0x3F;
    buffer->month			&= 0x1F;
    buffer->dayName			&= 0x07;
     
    buffer->alrt_minute		&= 0x7F;
    buffer->alrt_hour		&= 0x7F;
    buffer->alrt_day		&= 0x7F;
    buffer->alrt_dayName	&= 0x7F;
}
  
void rtcSetCtrl2(uint8_t mask)
{
	//buff[] = { control_2_register , mask };
	rx8564Writes( buff , sizeof(buff) );
}
 
void rtcSetTimer_control(uint8_t mask)
{
	//buff[] = { timer_control_register , mask };
	rx8564Writes( buff , sizeof(buff) );
}

uint8_t rtcReadTim(void)
{	
	//buff[] = { timer_register };
	rx8564Reads( buff , sizeof(buff) );

	return buff[0];
}