/* Generated by Header_Generator V1.0 */

/*
* Project Name -> Portexpander - MCP23017
* Version      -> 1.0
* Author       -> Hm
* Build Date   -> 24.04.2017
* Description  -> Driver
*
*
*
*/

#include <avr/io.h>
#include "../includes/i2cmaster.h"
#include "../includes/mcp23017.h"


void Mcp23017Init( uint8_t uiCnfgA , uint8_t uiCnfgB )
{
	i2c_init();
	i2c_start_wait(MCP23017_ADDR + I2C_WRITE);
	i2c_write(IODIRA);
	i2c_write(uiCnfgA);
	i2c_write(IODIRB);
	i2c_write(uiCnfgB);
	i2c_stop();	
}

void Mcp23017SetGPA( uint8_t uiCmd )
{	
	i2c_start_wait(MCP23017_ADDR + I2C_WRITE);
	i2c_write(GPIOA);
	i2c_write(uiCmd);
	i2c_stop();
};

void Mcp23017SetGPB( uint8_t uiCmd )
{	
	i2c_start_wait(MCP23017_ADDR + I2C_WRITE);
	i2c_write(GPIOB);
	i2c_write(uiCmd);
	i2c_stop();
};

