/* Generated by Header_Generator V1.0 */

/*
* Project Name -> MCP23017
* Version      -> 1.0
* Author       -> Hm
* Build Date   -> 24.04.2017
* Description  -> 
*
*
*
*/

#ifndef __MCP23017_H__
#define	__MCP23017_H__

#include <avr/io.h>
#include "i2cmaster.h"
#include "mcp23017.h"


void mcp23017Init	( void )
{
	i2c_start_wait(MCP23017_ADDR + I2C_WRITE);
	
	cmd = GPIOS_COMP_AS_OUT; 

	i2c_write	( IODIRA );
	i2c_write	( 0 );
	i2c_write	( IODIRB );
	i2c_write	( 0 );
	i2c_stop();
	
	mcp23017SetGPA( 0 );
	mcp23017SetGPB( 0 );
	
}

void mcp23017SetGPA	( uint8_t cmd )
{	
	i2c_start_wait	( MCP23017_ADDR + I2C_WRITE );
	i2c_write		( GPIOA );
	i2c_write		( cmd );
	i2c_stop();
}

void mcp23017SetGPB	( uint8_t cmd )
{	
	i2c_start_wait	( MCP23017_ADDR + I2C_WRITE );
	i2c_write		( GPIOB );
	i2c_write		( cmd );
	i2c_stop();
}

#endif