/* Generated by CodeDescriptor 1.5.0.0907 */
/*
* Project Name      -> Software I2C Implementation
* Version           -> 1.0.0.0404
* Author            -> Hm @ Workstadion
* Build Date        -> 04.04.2019 06:11:45
* Description       -> **DEBUG** Version
*
*
*
*/

#define F_CPU	16e6

#include <avr/io.h>
#include <util/delay.h>

#include "i2csoft.h"


void I2cSoftInit( void ) 
{	
	_I2C_PORT &= ( ( 1<<_I2C_SCL_BP ) | ( 1<<_I2C_SDA_BP ) );
	
	_I2C_PORT_SDA_HIGH;
	_I2C_PORT_SCL_HIGH;
}

void I2cSoftStart( void )
{
	_I2C_PORT_SCL_HIGH;
	H_DEL;
	
	_I2C_PORT_SDA_LOW;
	H_DEL;
}

void I2cSoftStop( void )
{
	_I2C_PORT_SDA_LOW;
	H_DEL;
	
	_I2C_PORT_SCL_HIGH;
	Q_DEL;
	
	_I2C_PORT_SDA_HIGH;
	H_DEL;
}

uint8_t I2cSoftWrite( uint8_t Data )
{
	static uint8_t Acknowledge = 0;
	uint8_t ui;
	
	for ( ui = 0 ; ui < 8 ; ui++ )
	{
		_I2C_PORT_SCL_LOW;
		Q_DEL;
		
		if ( Data & 0x80 )
		{
			_I2C_PORT_SDA_HIGH;
		}else
		{
			_I2C_PORT_SDA_LOW;
		}
		
		H_DEL;
		_I2C_PORT_SCL_HIGH;
		H_DEL;
		
 		while ( ( __PORT_PIN__( &_I2C_PORT ) & ( 1<<_I2C_SCL_BP ) ) == 0 ); // Warten bis "Scl" Low..
		
		Data <<= 1;
	}


	_I2C_PORT_SCL_LOW; // Ack Bestätigung
	Q_DEL;
	
	_I2C_PORT_SDA_HIGH;
	H_DEL;
	
	_I2C_PORT_SCL_HIGH;
	H_DEL;
		
	Acknowledge = !( __PORT_PIN__( &_I2C_PORT ) & ( 1<<_I2C_SDA_BP ) );
	
	_I2C_PORT_SCL_LOW;
	H_DEL;
	
	return Acknowledge;	
}

 uint8_t I2cSoftRead( uint8_t Acknowledge )
 {
	 uint8_t uiData = 0;
	 uint8_t ui;
	 
	 for ( ui = 0 ; ui < 8 ; ui++ )
	 {
		_I2C_PORT_SCL_LOW;
		H_DEL;
		_I2C_PORT_SCL_HIGH;
		H_DEL;	

		while( ( __PORT_PIN__( &_I2C_PORT ) & ( 1<<_I2C_SCL_BP ) ) == 0 );
		
		if( __PORT_PIN__( &_I2C_PORT ) & ( 1<<_I2C_SDA_BP ) )
		{
			uiData |= ( 0x80 >> ui );
		}
	 }

	_I2C_PORT_SCL_LOW;
	Q_DEL;

	if ( Acknowledge )
	{
		_I2C_PORT_SDA_LOW;
	}else
	{
		_I2C_PORT_SDA_HIGH;
	}
	H_DEL;
	
	_I2C_PORT_SCL_HIGH;
	H_DEL;
	
	_I2C_PORT_SCL_LOW;
	H_DEL;
			
	return uiData;
 }
 
















