/* Generated by CodeDescriptor 1.5.0.0907 */
/*
* Project Name      -> Software I2C Implementation
* Version           -> 1.0.0.0404
* Author            -> Hm @ Workstadion.: QP-01-02
* Build Date        -> 04.04.2019 06:11:45
* Description       -> **DEBUG** Version
*
*
*
*/

#ifndef __I2CSOFT_H__
#define ___I2CSOFT_H__

#ifndef F_CPU
#define F_CPU	16e6
#endif

#include <avr/io.h>
#include <util/delay.h>

#ifdef __AVR__

#define	__PORT_DDR__( _p )		(*( (_p-1) ))	
#define __PORT_PIN__( _p )		(*( (_p-2) ))

#define _I2C_PORT					PORTC
#define _I2C_SDA_BP					1
#define _I2C_SCL_BP					0

#define _I2C_PORT_SDA_HIGH			__PORT_DDR__( &_I2C_PORT ) &= ~(1<<_I2C_SDA_BP)
#define _I2C_PORT_SDA_LOW			__PORT_DDR__( &_I2C_PORT ) |=  (1<<_I2C_SDA_BP)

#define _I2C_PORT_SCL_HIGH			__PORT_DDR__( &_I2C_PORT ) &= ~(1<<_I2C_SCL_BP)
#define _I2C_PORT_SCL_LOW			__PORT_DDR__( &_I2C_PORT ) |=  (1<<_I2C_SCL_BP)

#define Q_DEL _delay_loop_2(1)
#define H_DEL _delay_loop_2(1)

#else

#error Library not supported for our Device \
please Contact.: "J.Homann@jh-elec.de"
#endif 




void I2cSoftInit( void );

void I2cSoftStart( void );

void I2cSoftStop( void );

uint8_t I2cSoftWrite( uint8_t Data );

uint8_t I2cSoftRead( uint8_t Acknowledge );


#endif 