/* Generated by CodeDescriptor 1.5.0.0907 */
/*
* Project Name      -> HC05
* Version           -> 1.0.0.1204
* Author            -> Hm @ Workstadion.: QP-01-02
* Build Date        -> 04.12.2017 11:11:37
* Description       -> Description
*
*
*
*/

#ifndef _HC0x_H_
#define _HC0x_H_

/*
*	choose your module
*/
//#define HC05
#define HC06

/*
*	commando transmit delay
*/
#define COMMAND_TRANSMIT_DELAY		250


#define HC05_EOC					"\r\n" // end of command string

typedef struct{
	
	/*
	*	hc05 buffer for commands
	*	dont touch!
	*/
	#ifdef HC05
	char tx[10][25];
	#endif
	
	#ifdef HC06
	char tx[10][20];
	#endif 
	/*
	*	how much data is in hc05 tx buffer..
	*	only for internal operation
	*	dont touch!
	*/
	uint8_t dataInBuff;
	
	/*
	*	number of bluetooth device is found
	*/
	#ifdef HC05
	uint8_t addrFound;
	
	/*
	*	buffer for founded bluetooth addresses
	*/
	char addr[9][15];	
	#endif
	/*
	*	crc from received string
	*/
	uint8_t crc;
	
}hc0x_t;
extern hc0x_t blth;


typedef char *(*waitForOkPtr)(char *);
char *waitForOk(char *inBuff);

/*
*	extended function for hc06
*/
typedef char *(*waitForxPtr)(char *, char *);
char *waitForx(char *inBuff, char *waitFor);


typedef char *(*connectPtr)(char *, char *, char *);
char *connect(char *addr, char *tmeOut, char *inBuff);

typedef char* (*getBlthNamePtr)(char *, char *);
char *getBlthName(char *addr, char *inBuff);

typedef char* (*scanForDevicesPtr)(char *);
char *scanForDevices(char *inBuff);

typedef char *(*getStatePtr)(char *);
char *getState(char *inBuff);

typedef void (*cmdToBuffPtr)(char *, hc0x_t *);
void cmdToBuff(char *buff, hc0x_t *blth);

typedef void (*buildCmdPtr)(const char *, char *);
void buildCmd(const char *cmd, char *para);

typedef void (*txBufferPtr)(hc0x_t *);
void txBuffer(hc0x_t *buff);

typedef void (*clearTxBuffPtr)(hc0x_t *);
void clearTxBuff(hc0x_t *blth);

typedef struct{
	
	waitForOkPtr		    waitForOk;
	connectPtr				connect;
	getBlthNamePtr			getBlthName;
	scanForDevicesPtr		scanForDevices;
	getStatePtr				getState;
	cmdToBuffPtr			cmdToBuff;
	buildCmdPtr				buildCmd;
	txBufferPtr				txBuffer;
	clearTxBuffPtr			clearTxBuff;
	
}hc05_fnc;

typedef struct{
	
	waitForxPtr			    waitForx;
	cmdToBuffPtr			cmdToBuff;
	buildCmdPtr				buildCmd;
	txBufferPtr				txBuffer;
	clearTxBuffPtr			clearTxBuff;
	
}hc06_fnc;

extern hc05_fnc hc05;
extern hc06_fnc hc06;

extern const char *hc06Cmd[];

bool readRingBuff(char *buff);

#endif