/* Generated by CodeDescriptor 1.3.0.0714 */
/*
* Project Name      -> TMP102
* Version           -> 1.0.0.0816
* Author            -> Hm @ Workstadion.: QP-01-02
* Build Date        -> 16.08.2017 06:29:22
* Description       -> Description
*
*
*
*/


#ifndef		TMP_102_H
#define		TMP_102_H

#define TMP102_ADDR	(0x49<<1)

enum tmp102Bytes
{
	TMP102_MSB,
	TMP102_LSB,	
	
	TMP102_BYTES
};

typedef struct  
{
	/*
	*	Status Bits
	*/
	uint8_t state;
	
	/*
	*	Niedrigst gemessene Temperatur
	*/
	int8_t lowest;
	
	/*
	*	Aktuell gemessene Temperatur
	*/
	int8_t actual;
	
	/*
	*	Höchst gemessene Temperatur
	*/
	int8_t highest;
	
}tmp102_t;

extern tmp102_t tmp102;


/* tmp102Read
* @para             -> -none
* @return           -> ad value from sensor
* @description      -> -none
*/
int16_t tmp102Read(void);


/* tmp102Calc
* @para             -> ad value from sensor
* @return           -> temp in °C
* @description      -> -none
*/
int16_t tmp102Calc(uint16_t temp);


/* tmp102GetTemp
* @para             -> -none
* @return           -> Temperature in °C
* @description      -> Get actual Temperature
*/
int8_t tmp102GetTemp( void );

#endif