/* Generated by CodeDescriptor 1.3.0.0714 */
/*
* Project Name      -> TMP102
* Version           -> 1.0.0.0816
* Author            -> Hm @ Workstadion.: QP-01-02
* Build Date        -> 16.08.2017 06:29:22
* Description       -> Description
*
*
*
*/


#ifndef		__TMP_102_H__
#define		__TMP_102_H__

#define TMP102_ADDR	(0x49<<1)

/* tmp102_read
* @para             -> -none
* @return           -> ad value from sensor
* @description      -> -none
*/
uint16_t tmp102_read(void);


/* tmp102_calc
* @para             -> ad value from sensor
* @return           -> temperature in °C
* @description      -> -none
*/
int16_t tmp102_calc(uint16_t temp);

#endif