/* Generated by CodeDescriptor 1.3.0.0714 */
/*
* Project Name      -> TMP102
* Version           -> 1.0.0.0816
* Author            -> Hm @ Workstadion.: QP-01-02
* Build Date        -> 16.08.2017 06:29:22
* Description       -> Description
*
*
*
*/

#include <avr/io.h>
#include "tmp_102.h"
#include "i2cmaster.h"

int16_t tmp102_calc(uint16_t temp){

	double stemp=temp;
	stemp *= 0.0625;
	
	return (int16_t)stemp;
}

uint16_t tmp102_read(void){
	
	uint8_t tmp[2]={0,0};
	
	i2c_rep_start(TMP102_ADDR+I2C_READ);
	tmp[0]=i2c_readAck();
	tmp[1]=i2c_readNak();
	i2c_stop();
	
	return (((uint16_t)tmp[0]<<4|tmp[1]>>3));
}