/* Generated by CodeDescriptor 1.0.0.0 */
/*
* Project Name      -> XMEGA - USART Driver
* Version           -> 1.0
* Author            -> Hm @ Workstadion.: QP-01-02
* Build Date        -> 16.06.2017 10:02:55
* Description       -> XMEGA USART Driver
*
*
*
*/

#ifndef __XMEGA_USART_H__
#define __XMEGA_USART_H__

#define BAUD( BAUD_ )			( ( ( F_CPU / ( 16UL * BAUD_ ) ) ) - 1 )

#define USARTxx					USARTE0
#define USART_PORT				PORTE
#define USART_TX_bp				3
#define USART_RX_bp				2

#define USART_RX_INT			USARTE0_RXC_vect
#define USART_TX_INT			USARTE0_TXC_vect
#define USART_DRE_INT			USARTE0_DRE_vect

#define USART_RX_BUFFER_SIZE	128
#define USART_TX_BUFFER_SIZE	32

/* size of RX/TX buffers */
#define USART_RX_BUFFER_MASK	( USART_RX_BUFFER_SIZE - 1)
#define USART_TX_BUFFER_MASK	( USART_TX_BUFFER_SIZE - 1)


#define USART_FRAME_ERROR		0x1000              /* Framing Error by UART       */
#define USART_OVERRUN_ERROR		0x0800              /* Overrun condition by UART   */
#define USART_PARITY_ERROR		0x0400              /* Parity Error by UART        */
#define USART_BUFFER_OVERFLOW	0x0200              /* receive ringbuffer overflow */
#define USART_NO_DATA			0x0100              /* no receive data available   */



typedef enum	
{
	BAUD_2400,
	BAUD_4800,
	BAUD_9600,
	BAUD_14400,
	BAUD_19200,
	BAUD_28800,
	BAUD_38400,
	BAUD_57600,
	BAUD_76800,
	BAUD_115200,
	BAUD_230400,
	BAUD_460800,
	BAUD_921600,
	BAUD_1382000,
	BAUD_1843000,
	BAUD_2000000,
}usart_baudrates_enum;


typedef struct	
{
	uint8_t bsel;
	int8_t bscale;
}usart_baud_setting;



/* usartInit
* @para             -> *USART = Welches Usart Modul? Baudrate?
* @return           -> -none
* @description      -> -none
*/
void	usartInit		( USART_t *usart , usart_baudrates_enum baud );

/* usart_c
* @para             -> s = Zeichen was gesendet werden soll
* @return           -> -none
* @description      -> -none
*/
void	usartPutChar	( char c );

/* usartPutStr
* @para             -> *str = Zeichenkette die gesendet werden soll
* @return           -> -none
* @description      -> -none
*/
void	usartPutStr		( char *str );

/* usartGetChar
* @para             -> -none
* @return           -> - Empfangenes Zeichen
* @description      -> Die unteren 8 Bit sind das Zeichen, die anderen 8 Bit sind erstmal als Reserve vorhanden
*/
uint16_t usartGetChar	( void );

#endif