/* Generated by CodeDescriptor 1.0.0.0 */
/*
* Project Name      -> XMEGA - USART Driver
* Version           -> 1.0
* Author            -> Hm @ Workstadion.: QP-01-02
* Build Date        -> 16.06.2017 10:02:55
* Description       -> XMEGA USART Driver
*
*
*
*/

#include <avr/io.h>
#include <avr/interrupt.h>
#include "xmega_usart.h"



void usart_init(USART_t *USART, uint16_t Baudrate)
{
	USART->BAUDCTRLB = 0;
	USART->BAUDCTRLA = BAUD(Baudrate);
	
	USART->CTRLA	 = USART_RXCINTLVL_HI_gc;
	USART->CTRLB	 = USART_TXEN_bm | USART_RXEN_bm;
	USART->CTRLC	 = USART_CHSIZE_8BIT_gc;
	
	USART_PORT.DIRSET	= (1<<USART_TX_bp);
	USART_PORT.DIRCLR	= (1<<USART_RX_bp);
}

void usart_c(char s){
	
	while (!(USARTxx.STATUS & USART_DREIF_bm));
	USARTxx.DATA = s;
}

void usart_str(char *str){
	
	while(*str)
	{
		usart_c(*str++);
	}
}




ISR(USARTC0_RXC_vect){} // }
ISR(USARTC0_TXC_vect){} // } Interrupt Vectors USARTC0

ISR(USARTC1_RXC_vect){} // }
ISR(USARTC1_TXC_vect){} // } Interrupt Vectors USARTC1

ISR(USARTD0_RXC_vect){} // } 
ISR(USARTD0_TXC_vect){} // } Interrupt Vectors USARTD0
	
ISR(USARTD1_RXC_vect){} // } 
ISR(USARTD1_TXC_vect){} // } Interrupt Vectors USARTD1
	
ISR(USARTE0_RXC_vect){} // }
ISR(USARTE0_TXC_vect){} // } Interrupt Vectors USARTE0
	
