/* Generated by CodeDescriptor 1.0.0.0 */
/*
* Project Name      -> XMEGA - USART Driver
* Version           -> 1.0
* Author            -> Hm @ Workstadion.: QP-01-02
* Build Date        -> 16.06.2017 10:02:55
* Description       -> XMEGA USART Driver
*
*
*
*/

#ifndef _XMEGA_USART_H
#define _XMEGA_USART_H

#ifndef F_CPU
	#define F_CPU	2000000
#endif

#define BAUD(BAUD_)		(((F_CPU/(16UL*BAUD_)))-1)

#define USARTxx			USARTC0
#define USART_PORT		PORTC
#define USART_TX_bp		3
#define USART_RX_bp		2

/* usart_init
* @para             -> *USART = Usart Unit, Baudrate = Baudrate for Transfere
* @return           -> -none
* @description      -> -none
*/
void usart_init(USART_t *USART, uint16_t Baudrate);

/* usart_c
* @para             -> s = Character to wish send
* @return           -> -none
* @description      -> -none
*/
void usart_c(char s);

/* usart_str
* @para             -> *str = String to wish send
* @return           -> -none
* @description      -> -none
*/
void usart_str(char *str);

#endif