/* Generated by CodeDescriptor 1.0.0.0 */
/*
* Project Name      -> XMEGA - USART Driver
* Version           -> 1.0
* Author            -> Hm @ Workstadion.: QP-01-02
* Build Date        -> 16.06.2017 10:02:55
* Description       -> XMEGA USART Driver
*
*
*
*/

#include <avr/io.h>
#include <avr/interrupt.h>
#include "xmega_usart.h"



void usartInit(USART_t *usart , uint16_t baud )
{
	if ( usart == NULL )
	{
		return;
	}
	
	usart->BAUDCTRLB = 0;
	usart->BAUDCTRLA = BAUD( baud );
	
	usart->CTRLA	 = USART_RXCINTLVL_HI_gc;
	usart->CTRLB	 = USART_TXEN_bm | USART_RXEN_bm;
	usart->CTRLC	 = USART_CHSIZE_8BIT_gc;
	
	USART_PORT.DIRSET	= ( 1 << USART_TX_bp );
	USART_PORT.DIRCLR	= ( 1 << USART_RX_bp );

	PMIC.CTRL = PMIC_LOLVLEN_bm | PMIC_MEDLVLEN_bm | PMIC_HILVLEN_bm;	

}

void usartChar( char c )
{
	
	while ( ! ( USARTxx.STATUS & USART_DREIF_bm ) );
	USARTxx.DATA = c;
}

void uartStr( char *str ) 
{	
	while( *str )
	{
		usartChar( *str++ );
	}
}



ISR( USART_RX_INT )
{
	
}

ISR( USART_TX_INT )
{
	
}

	
