/* Generated by CodeDescriptor 1.0.0.0 */
/*
* Project Name      -> XMEGA - USART Driver
* Version           -> 1.0
* Author            -> Hm @ Workstadion.: QP-01-02
* Build Date        -> 16.06.2017 10:02:55
* Description       -> XMEGA USART Driver
*
*
*
*/

#ifndef __XMEGA_USART_H__
#define __XMEGA_USART_H__

#ifndef F_CPU
	#define F_CPU	2000000
#endif

#define BAUD( BAUD_ )	( ( ( F_CPU / ( 16UL * BAUD_ ) ) ) - 1 )

#define USARTxx			USARTC0
#define USART_PORT		PORTC
#define USART_TX_bp		3
#define USART_RX_bp		2

#define USART_RX_INT	USARTC0_RXC_vect
#define USART_TX_INT	USARTC0_TXC_vect

/* usartInit
* @para             -> *USART = Usart Unit, Baudrate = Baudrate for Transfere
* @return           -> -none
* @description      -> -none
*/
void usartInit ( USART_t *usart , uint16_t baud );

/* usart_c
* @para             -> s = Character to wish send
* @return           -> -none
* @description      -> -none
*/
void usartChar ( char c );

/* usartStr
* @para             -> *str = String to wish send
* @return           -> -none
* @description      -> -none
*/
void usartStr ( char *str );

#endif