/* Generated by CodeDescriptor 1.5.0.0907 */
/*
* Project Name      -> Taster lesen
* Version           -> 1.0.0.0328
* Author            -> Hm @ Workstadion.: QP-01-02
* Build Date        -> 28.03.2019 07:37:32
* Description       -> **DEBUG**
*
*
*
*/

#include <avr/io.h>
#include "Switch.h"

/* Prototypen */

void SwitchInit( volatile uint8_t *SwitchInPort , uint8_t SwitchMask , Switch_t *Switch )
{
	PORT_DDR_ADDR(SwitchInPort) &= ~( SwitchMask );
	Switch->Old = 0;
	Switch->New = 0;
	Switch->Info = 0;
	Switch->Mask = SwitchMask;
}

void SwitchRead( Switch_t *Switch , volatile uint8_t *SwitchInPort )
{
	Switch->New = ( ( PORT_PIN_ADDR( SwitchInPort ) & Switch->Mask ) ^ Switch->Mask );
	
	if (Switch->New != Switch->Old) // Eingang geaendert
	{
		Switch->Info = ( Switch->Info | ( Switch->New & ( Switch->Old ^ Switch->New ) ) );
	}
	
	Switch->Old = Switch->New;
}

void SwitchClear( Switch_t *Switch )
{
	Switch->Old = 0;
	Switch->New = 0;
	Switch->Info = 0;
}

/* Ende Prototypen */