/* Generated by CodeDescriptor 1.5.0.0907 */
/*
* Project Name      -> Taster lesen
* Version           -> 1.0.0.0328
* Author            -> Hm @ Workstadion.: QP-01-02
* Build Date        -> 28.03.2019 07:37:32
* Description       -> **DEBUG**
*
*
*
*/

#ifndef __SWITCH_H__
#define __SWITCH_H__


/*	Macro 
*	- Calculate Address of Data Direction Register
*	from
*/
#define PORT_DDR_ADDR( PORT )		(*( (PORT-1) ))

/*	Macro 
*	- Calculate Address of PIN Register
*	from
*/
#define PORT_PIN_ADDR( PORT )		(*( (PORT-2) ))

typedef struct
{
	uint8_t New;
	uint8_t Old;
	uint8_t Info;
	uint8_t Mask;
}Switch_t;


void SwitchInit( volatile uint8_t *SwitchInPort , uint8_t SwitchMask , Switch_t *Switch );

void SwitchRead( Switch_t *Switch , volatile uint8_t *SwitchInPort );

void SwitchClear( Switch_t *Switch );

#endif