/* Generated by CodeDescriptor 1.5.0.0907 */
/*
* Project Name      -> Kommando Interpreter
* Version           -> 1.0.1.1124
* Author            -> Hm @ Workstadion.: QP-01-02
* Build Date        -> 20.09.2017 07:50:01
* Description       -> Description
*
*
*
*/

#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>

#include "cmd.h"


// const cmdTable_t cmdTab[] =
// {
// 	{"Relais_Handler!" 			, 	"-REL"		, 	NULL 	},
// 
// };
// 
// cmd_t cmd =
// {
// 	.table	= cmdTab,
// 	.tabLen = sizeof( cmdTab ) / sizeof( *cmdTab ),
// 	.raw 	= &raw
// };


static uint8_t 		cmdCntPara			( char *cmd )								
{
	uint8_t x = 0;
	char *cmdPtr = cmd;
	char *beginnPtr = cmd;
	
	beginnPtr = strchr( beginnPtr , ':' ); // Erster Parameter
	if ( beginnPtr != NULL )
	{
		if ( *(beginnPtr + 1 ) != ';' )
		{
			x++;	
		}
	}
	
	for ( ; cmdPtr != NULL ;  )
	{
		cmdPtr = strchr( cmdPtr + 1 , ',' ); // weitere Parameter
		x++;
	}
	
	return ( x - 1 );
}

static char			*cmdSearch			( char *inBuff , char *srchCmd )			
{
	/*
	*	Zeiger deklarieren).
	*/
	char *inBuffPtr		= inBuff;
	char *srchCmdPtr	= srchCmd;
	char *cmdBeginnPtr 	= NULL;
	char *cmdEndPtr		= NULL;
	
	if ( inBuffPtr == NULL || srchCmdPtr == NULL )
	{
		return NULL;
	}

	cmdBeginnPtr = strstr( inBuffPtr , srchCmdPtr );
	cmdEndPtr	 = strchr( inBuffPtr , CMD_DATA_END );	      

	if ( cmdEndPtr == NULL || cmdBeginnPtr == NULL )
	{
		return NULL;
	}
		
	return cmdBeginnPtr;
}

static int8_t		cmdGetIndex			( cmd_t *cmd , char *inBuff )				
{
	uint8_t i;
	
	cmd_t 	*cmdPtr			= cmd;
	char  	*cmdSearchPtr 	= NULL;
	char	*inputPtr		= inBuff;

	for ( i = 0 ; i < cmdPtr->tabLen ; i++ )
	{
		cmdSearchPtr = cmdSearch( inputPtr , ( char* ) cmdPtr->table[i].instruction );
		
		if ( cmdSearchPtr != NULL )
		{
			return i;
		}
	}
	
	return -1;	
}


const char			*cmdGetInstruction	( cmd_t *cmd , char *input )				
{
	int8_t i = cmdGetIndex( cmd , input );
	
	if ( i != (int8_t) -1 )
	{
		return cmd->table[i].instruction;
	}
	
	return NULL;
}

const char			*cmdGetName			( cmd_t *cmd , char *input )				
{
	int8_t ret = cmdGetIndex( cmd , input );
	
	if ( ret != (int8_t) -1 )
	{
		return cmd->table[ret].name;
	}
		
	return NULL;
}

void				cmdGetFunc			( cmd_t *cmd , char *input )				
{
	int8_t ret = cmdGetIndex( cmd , input );
	if ( ret != (int8_t) -1 )
	{
		cmd->table[ret].fnc( NULL , NULL );
	}
}

char 				*cmdGetPara 		( cmd_t *cmd , char *input , uint8_t num )	
{
	char 		*delimiter 	= NULL;
	char 		*cmdEndPtr	= NULL;
	const char 	*rawPtr		= NULL;
	
	static char buff[20] = "";
	
	uint8_t x;
	
	for ( x = 0 ; x < cmd->tabLen ; x++ )
	{
		rawPtr = ( const char *) cmdSearch( input , ( char * ) cmd->table[x].instruction );
		if ( rawPtr != NULL )
		{
			break;
		}
	}
	
	if( rawPtr == NULL )
	{
		return NULL;
	}
	
	cmd->raw->paraNumb = cmdCntPara( ( char * ) rawPtr );
	
	cmdEndPtr = strchr( rawPtr , ';' );	
	if( cmdEndPtr == NULL )
	{
		return  NULL;
	}

	delimiter = strchr( rawPtr , ':' ) + 1;
	if( ( delimiter - 1 ) == NULL )
	{
		return  NULL;
	}

	delimiter = strtok( delimiter , CMD_RAW_PARA_DELIMITER );
	if( delimiter == NULL )
	{
		return  NULL;
	}
	
	for ( x = 0 ; x < num || x < cmd->raw->paraNumb ; x++ )
	{
		delimiter = strtok( NULL , CMD_RAW_PARA_DELIMITER );			
	}
	
	strcpy( buff , delimiter );
	char *ptr = strchr( buff , ';' );
	*ptr = '\0';
	
	return buff; 
}

