/* Generated by CodeDescriptor 1.5.0.0907 */
/*
* Project Name      -> Kommando Interpreter
* Version           -> 1.0.1.1124
* Author            -> Hm @ Workstadion.: QP-01-02
* Build Date        -> 20.09.2017 07:50:01
* Description       ->	Datentypen  
*
*/

#ifndef __CMD_TYPES_H__
#define __CMD_TYPES_H__


enum Cmd_Data_Type_Enum
{
    DATA_TYP_UINT8,
    DATA_TYP_UINT16,
    DATA_TYP_UINT32,
    DATA_TYP_FLOAT,
    DATA_TYP_STRING,

    DATA_TYP_INT8,
    DATA_TYP_INT16,
    DATA_TYP_INT32,

    __DATA_TYP_MAX_INDEX__
};


typedef struct
{
	enum Cmd_Data_Type_Enum eDataTypes;
	uint8_t uiDataType;
}CmdDataTypes_t;

#endif 
