/* Generated by CodeDescriptor 1.5.0.0907 */
/*
* Project Name      -> WSQ3000
* Version           -> 1.0.0.0727
* Author            -> Hm @ Workstadion.: QP-01-02
* Build Date        -> 27.07.2018 06:11:48
* Description       -> Kommandoliste
*
*	Kommandos für die Serielle Schnittstelle
*
*/

#ifndef __CMD_TAB_H__
#define __CMD_TAB_H__

#include <avr/io.h>
#include <stdlib.h>
#include "cmd.h"



/*
*	+++++++++++++++++++++++++++++++++++++++++++++++
*	+ Parameter | Beschreibung Name des Kommandos + 
*	+++++++++++++++++++++++++++++++++++++++++++++++
*		1			Name des Kommandos
*		2			Kommando was z.B über die Serielle Schnittstelle empfangen werden muss damit eine Aktion erfolgt
*		3			Funktion die ausgeführt werden soll	
*					( muss später auf den gewünschten Datentypen ( Rückgabe & Übergabeparameter ) gecastet werden
*/

const		cmdTable_t		cmdTab[] =					
{
	{"Relais:" 			, 	"-k"	, 	relaisHandler	,	":Relais , 0=off || 1=on"	},
	{"Init:"			,	"-init"	,	reInit			,	"0"						},
	{"EEP:"				,	"-eep"	,	loadEEP_		,	"0"						},
	{"Kalibration:"		,	"-cal"	,	cal				,	"0"						},
	{"Spannung:"		,	"-getv"	,	getVoltage		,	"0"						},
	{"Strom:"			,	"-geti"	,	NULL			,	"0"						},
	{"Help  :"			,	"-help"	,	helper			,	"0"						},
};

#endif