/* Generated by CodeDescriptor 1.5.0.0907 */
/*
* Project Name      -> Kommando Interpreter
* Version           -> 1.0.1.1124
* Author            -> Hm @ Workstadion.: QP-01-02
* Build Date        -> 20.09.2017 07:50:01
* Description       ->	Exitcodes
*
*/

#ifndef __EXITCODES_H__
#define __EXITCODES_H__


enum eExitcodes
{
	EXITCODE_OK,
	EXITCODE_FAIL,
	EXITCODE_NOT_EXIST,

	/*
	*	andere Projekt spezifische Codes
	*/

	__EXITCODE_MAX_ENTRYS__
};

#endif
