/* Generated by CodeDescriptor 1.5.0.0907 */
/*
* Project Name      -> Kommando Interpreter
* Version           -> 1.0.1.1124
* Author            -> Hm @ Workstadion.: QP-01-02
* Build Date        -> 20.09.2017 07:50:01
* Description       ->
*
*
*	++ Telegramm Aufbau ++
*
*
*	'-' | '+ ' | | 0x05 | | 0x01 | | 0x04 | | 0x00 | | 0x32 | | 0..n ( max. 255 Bytes) |
*	+----------+ +------+ +------+ +------+ +------+ +------+ +------------------------+
*		 ^			^		 ^		   ^		^		 ^				  ^
*		 |			|		 |		   |		|		 |				  |
*	Startzeichen    |	  Datentyp	   |	Exitcode	 |			  Nutzdaten
*					|				   |				 |			  Anmerkung: Bei Datentypen > uint8_t
*			Länge des gesamten		   |			Checksumme		  wird das LSB zuerst gesendet.
*			Telegrammes				   |
*							Telegramm Identifikation
*
*
*	1.: Initalisierung der ganzen Struktur + Callback für die Sendefunktion
*
*/

#ifndef __FRAME_H__
#define __FRAME_H__

#include <stdint.h>
#include <stdlib.h>

#include "frame_types.h"
#include "exitcodes.h"
#include "frame_id.h"

#ifndef _WIN32
    #include "uart.h"
#endif

#ifndef NULL
	#define NULL 0
#endif


/*
*	Callback Funktion zum senden von Frames..
*	2 Parameter müssen übergeben werden ->
*
*	1 = Zeiger auf Daten ( *uint8_t )
*	2 = Länge
*/
#ifndef _WIN32
    #define _CMD_SEND_CB_FNC_PTR_		uartPutByteStr
#endif


enum Cmd_Communication_Header_Enum
{
	CMD_HEADER_LENGTH_OF_FRAME, /**< Länge des gesamten Frames */
	CMD_HEADER_DATA_TYP, 		/**< Welcher Datentyp wird versendet */
	CMD_HEADER_ID, 				/**< Frame Identifikation */
	CMD_HEADER_EXITCODE,		/**< Rückgabewert von Funktion */
	CMD_HEADER_CRC, 			/**< Checksumme von der ganzen Nachricht */

	__CMD_HEADER_ENTRYS__
};

typedef struct
{
    /**< Datentyp der Nutzdaten im Frame */
	enum Cmd_Data_Type_Enum	eDataType;

    /**< Gibt an um welche Art Frame es sich handelt */
	enum Cmd_Ident_Enum	eMessageID;

    /**< Funktions Rückgabe Code */
	enum Cmd_Exitcodes_Enum	eExitcode;

    /**< Nutzdaten */
	uint8_t *pData;

    /**< Laenge der Nutzdaten */
	uint8_t uiDataLength;

}sFrameDesc_t;

typedef struct
{
    /**< Zeiger auf den Anfang des Frames */
	uint8_t *puiFrame;

	/**< Länge des kompletten Frames */
	uint8_t uiLength;

    /**< Gesendete Datentyp */
	enum Cmd_Data_Type_Enum	eDataType;

}sFrame_t;

typedef struct
{
    /**< Intern berechnete Checksumme */
	uint8_t uiInternal;

    /**< Extern berechnete Checksumme */
	uint8_t uiExternal;

}sCrc_t;


void		FrameInit			( sFrameDesc_t *psFrame );

void		FrameClear			( sFrameDesc_t *psFrame );

uint8_t		FrameParse			( uint8_t *pReceive , sFrameDesc_t *psFrame , uint16_t uiBufferLength );

void		FrameBuild  		( sFrameDesc_t *psFrame ,
								  enum Cmd_Ident_Enum eIdent ,
								  enum Cmd_Data_Type_Enum eDataType ,
								  enum Cmd_Exitcodes_Enum eExitcode ,
								  uint8_t *pData,
								  uint8_t DataLength
                                );

void		FrameSend   		( sFrameDesc_t *psFrame );



/**< DEBUG */

#ifdef _WIN32
    void        FrameShow      ( sFrameDesc_t *psFrame );
#endif

#endif // __FRAME_H__
