/* Generated by CodeDescriptor 1.5.0.0907 */
/*
* Project Name      -> Kommando Interpreter
* Version           -> 1.0.1.1124
* Author            -> Hm @ Workstadion.: QP-01-02
* Build Date        -> 20.09.2017 07:50:01
* Description       ->	Identifikations Codes
*
*/

#ifndef __ID_H__
#define __ID_H__


enum eIdent
{
	ID_PING = 0, // Darauf sollte die Firmware ein Lebenszeichen melden
	ID_VERSION,

	/*	Hier werden Projekt spezifische
	*	Identifikations Codes eingetragen
	*/

		/*...*/

	/*
	*	Ende der Projekt spezifischen Identifikations Codes
	*/

	ID_APPLICATION = 255 // Für irgendwelche System spezifischen Meldungen
};

#endif
