/* Generated by CodeDescriptor 1.5.0.0907 */
/*
* Project Name      -> WSQ 3000
* Version           -> 1.0.0.0813
* Author            -> Hm @ Workstadion.: QP-01-02
* Build Date        -> 13.08.2018 10:10:01
* Description       -> Timer
*
*
*
*/


#ifndef __TIMER_H__
#define __TIMER_H__


#include "wsq3000_def.h"

#define TIMER_HZ				100
#define TIMER_PRESCALER			1024

#if		TIMER_PRESCALER == 1
#undef TIMER_PRESCALER_gc
#define TIMER_PRESCALER_gc	TC_CLKSEL_DIV1_gc
#elif	TIMER_PRESCALER == 2
#undef TIMER_PRESCALER_gc
#define TIMER_PRESCALER_gc	TC_CLKSEL_DIV2_gc
#elif	TIMER_PRESCALER == 4
#undef TIMER_PRESCALER_gc
#define TIMER_PRESCALER_gc	TC_CLKSEL_DIV4_gc
#elif	TIMER_PRESCALER == 8
#undef TIMER_PRESCALER_gc
#define TIMER_PRESCALER_gc	TC_CLKSEL_DIV8_gc
#elif	TIMER_PRESCALER == 64
#undef TIMER_PRESCALER_gc
#define TIMER_PRESCALER_gc	TC_CLKSEL_DIV64_gc
#elif	TIMER_PRESCALER == 256
#undef TIMER_PRESCALER_gc
#define TIMER_PRESCALER_gc	TC_CLKSEL_DIV256_gc
#elif	TIMER_PRESCALER == 1024
#undef TIMER_PRESCALER_gc
#define TIMER_PRESCALER_gc	TC_CLKSEL_DIV1024_gc
#endif


/*
*	Einige XMEGA´s haben mehrere Timer Compare Matches
*/
#define TIMER_CALC			(uint16_t)( ( F_CPU / ( 2 * TIMER_PRESCALER ) * ( TIMER_HZ + 1 ) ) )


void timer0OVFInit	( TC0_t *tim );

void timer0CMPInit	( TC0_t *tim );

void timerStart		( TC0_t *tim0 , TC1_t *tim1 );

void timerStop		( TC0_t *tim0 , TC1_t *tim1 );


#endif
