/* Generated by CodeDescriptor 1.5.0.0907 */
/*
* Project Name      -> Number Converter
* Version           -> 1.0.0.0927
* Author            -> Hm @ Workstadion.: QP-01-02
* Build Date        -> 27.09.2017 07:58:53
* Description       -> Convert Numbers in other Systems.
*
*
*
*/

#include <stdint.h>

#ifndef __CONVERT_H__
#define __CONVERT_H__



/*Prototypes*********************************************************************/

char *uiDecHex8( uint8_t uiDec, char *pcBuffer )

char *uiDecHex16( uint16_t uiDec, char *pcBuffer )

char *uiDecHex32( uint32_t uiDec, char *pcBuffer )

char *uiDecBcd8( uint8_t uiDec, char *pcBuffer )

char *uiDecBin8( uint8_t uiDec, char *pcBuffer )

/*End Prototypes*********************************************************************/

#endif
