/* Generated by CodeDescriptor 1.5.0.0907 */
/*
* Project Name      -> Number Converter
* Version           -> 1.0.0.0927
* Author            -> Hm @ Workstadion.: QP-01-02
* Build Date        -> 27.09.2017 07:58:53
* Description       -> Convert Numbers in other Systems.
*
*	01.04.19 ->	uiDecBin8 überarbeitet	
*
*/


#include <avr/io.h>
#include "convert.h"


/* uiDecHex8()
* @para             -> uiDec , *pcBuffer
* @return           -> *pcBuffer
* @description      -> Convert "uiDec" to Hexadecimal
*					   Buffer must have size of 5 
*/
char *uiDecHex8( uint8_t uiDec, char *pcBuffer )
{	
	/* hex char set */
	char HexChars[] = "0123456789ABCDEF";
	
  	pcBuffer[0] = '0';	
   	pcBuffer[1] = 'x'; 	 
	
    pcBuffer[2] = HexChars[uiDec >>  4 & 0xF];          
    pcBuffer[3] = HexChars[uiDec       & 0xF];
	
	pcBuffer[4] = '\0';
	
    return pcBuffer;
}

/* uiDecHex16()
* @para             -> uiDec , *pcBuffer
* @return           -> *pcBuffer
* @description      -> Convert "uiDec" to Hexadecimal
*					   Buffer must have size of 7 
*/
char *uiDecHex16( uint16_t uiDec, char *pcBuffer )
{	
	/* hex char set */
	char HexChars[] = "0123456789ABCDEF";
	
  	pcBuffer[0] = '0';	
   	pcBuffer[1] = 'x'; 	
	
    pcBuffer[2] = HexChars[uiDec >> 12 & 0xF];  	
    pcBuffer[3] = HexChars[uiDec >>  8 & 0xF];     
    pcBuffer[4] = HexChars[uiDec >>  4 & 0xF];          
    pcBuffer[5] = HexChars[uiDec       & 0xF];
	
	pcBuffer[6] = '\0';
	
    return pcBuffer;
}

/* uiDecHex32()
* @para             -> uiDec , *pcBuffer
* @return           -> *pcBuffer
* @description      -> Convert "uiDec" to Hexadecimal
*					   Buffer must have size of 11 
*/
char *uiDecHex32( uint32_t uiDec, char *pcBuffer )
{   
    /* hex char set */
    char HexChars[] = "0123456789ABCDEF";
	
    pcBuffer[0] = '0';  
    pcBuffer[1] = 'x';    
	
    pcBuffer[2] = HexChars[uiDec >> 28 & 0xF];     
    pcBuffer[3] = HexChars[uiDec >> 24 & 0xF];          
    pcBuffer[4] = HexChars[uiDec >> 20 & 0xF];
    pcBuffer[5] = HexChars[uiDec >> 16 & 0xF];      
    pcBuffer[6] = HexChars[uiDec >> 12 & 0xF];     
    pcBuffer[7] = HexChars[uiDec >>  8 & 0xF];          
    pcBuffer[8] = HexChars[uiDec >>  4 & 0xF];
    pcBuffer[9] = HexChars[uiDec       & 0xF];
	
	pcBuffer[10] = '\0';
		     
    return pcBuffer;
}

/* uiDecBcd8()
* @para             -> uiDec , *pcBuffer
* @return           -> *pcBuffer
* @description      -> Convert "uiDec" to Binary Coded Decimal
*					   Buffer must have size of 5 
*/
char *uiDecBcd8( uint8_t uiDec, char *pcBuffer )
{	
	/* hex sign */
	pcBuffer[0] = '0';
	pcBuffer[1] = 'x';

	pcBuffer[2] = ( uiDec / 10 ) + '0';
	pcBuffer[3] = ( uiDec % 10 ) + '0';
	
	pcBuffer[4] = '\0';
	
	return b;
}

/* uiDecBin8()
* @para             -> uiDec , *pcBuffer
* @return           -> *pcBuffer
* @description      -> Convert "uiDec" to Binary
*					   Buffer must have size of 9 
*/
char *uiDecBin8( uint8_t uiDec, char *pcBuffer )
{
	uint8_t uiValue = uiDec;
	uint8_t uiPos = 0;
	
	for( ; uiPos < 8 ; uiPos++ )
	{
		if ( uiValue & 0x80 ) 
	    {
			pcBuffer[uiPos] = '1';
		}
		else
		{
			pcBuffer[uiPos] = '0';
		}
		uiValue<<=1;
	}

	pcBuffer[++uiPos] = '\0';
	
	return pcBuffer;
}
