/* Generated by CodeDescriptor 1.2.0.0713 */
/*
* Project Name      -> SHT21
* Version           -> 1.0.0.0714
* Author            -> Hm @ Workstadion.: QP-01-02
* Build Date        -> 15.05.2019 07:34:00
* Description       -> Luftfeuchtigkeit & Temperatursensor
*
*
*
*/

#include <stdint.h>

#include "sht21.h"
#include "I2C.h"



static inline enum I2c_Return_Codes _Sht21ReadRegs( uint8_t *buff , uint8_t leng )
{
	I2cTransfer_t Rx;
	
	Rx.ptrData = buff;
	Rx.uiLength = leng;
	Rx.uiSlaveAddress = SHT21_ADDR;
	
	enum I2c_Return_Codes Exitcode = I2cReadBytes( &Rx );
		
	return (uint8_t)Exitcode;
}

static inline enum I2c_Return_Codes _Sht21WriteRegs( uint8_t *buff , uint8_t leng )
{
	I2cTransfer_t Tx;
	
	Tx.ptrData = buff;
	Tx.uiLength = leng;
	Tx.uiSlaveAddress = SHT21_ADDR;
	
	enum I2c_Return_Codes Exitcode = I2cWriteBytes( &Tx );
	
	return Exitcode;
}

static inline uint8_t _Sht21CalcCRC( uint8_t *data , uint8_t nbrOfBytes )
{
	// CRC
	//const u16t POLYNOMIAL = 0x131; //P(x)=x^8+x^5+x^4+1 = 100110001
	
	uint8_t byteCtr,bit,crc;
	
	crc = 0;
	
	//calculates 8-Bit checksum with given polynomial
	for (byteCtr = 0; byteCtr < nbrOfBytes; ++byteCtr)
	{
		crc ^= (data[byteCtr]);
		for (bit = 8; bit > 0; --bit)
		{
			if (crc & 0x80) crc = (crc << 1) ^ 0x131;
			else 		crc = (crc << 1);
		}
	}
	return(crc);
}


uint8_t Sht21Read( int16_t *temp , uint16_t *humidity )
{
	uint8_t d[3];
	uint32_t val;
	
	//=== Software reset =============================================
 	d[0] = CMD_SOFT_RST;
 	_Sht21WriteRegs( d , 1 );


	//=== User register ========================================================
	d[0] = CMD_RD_REG;
	_Sht21ReadRegs( d , 2 );

	if(d[1] == _Sht21CalcCRC(d,1))
	{
		uint8_t buff[] = { CMD_WR_REG , d[0] };
		_Sht21WriteRegs( buff , 2 );
	}


	//=== Temperature ===========================================================
	d[0] = CMD_TMP_HLD;
	_Sht21ReadRegs( d , 3 );
	
	if(d[2] == _Sht21CalcCRC(d,2))
	{
		val = d[0];
		val <<= 8;
		val += d[1];
		val &=  ~(0x0003);
		*temp = -46.85 + 175.72/65536 *(float)val;
	}
	
	//=== Humidity ==============================================================
	d[0] = CMD_HUM_HLD;
	_Sht21ReadRegs( d , 3 );
	
	if(d[2] == _Sht21CalcCRC(d,2))
	{
		val = d[0];
		val <<= 8;
		val += d[1];
		val &= ~0x0003;
		*humidity = 6.0 + 125.0/65536 * (float)val;
	}
	
	return(0);
}

uint8_t Sht21GetSerialNumber( uint8_t numb[8] )
{
	uint8_t d[8] = "";
	d[0] = 0xFA;
	d[1] = 0x0F;
	_Sht21WriteRegs( d , 2 );

	_Sht21ReadRegs( d , 8 );
	numb[5] = d[0];
	numb[4] = d[2];
	numb[3] = d[4];
	numb[2] = d[6];
	
	d[0] = 0xFC;
	d[1] = 0xC9;
	_Sht21WriteRegs( d , 2 );
	
	_Sht21ReadRegs( d ,  6 );
	numb[1] = d[0];
	numb[0] = d[1];
	numb[7] = d[3];
	numb[6] = d[4];

	return 0;
}





