/* Generated by CodeDescriptor 1.5.0.0907 */
/*
* Project Name      -> ATxmega Makros
* Version           -> 1.0.0.0903
* Author            -> Hm @ Workstadion.: QP-01-02
* Build Date        -> 03.09.2018 13:33:06
* Description       -> Einige hilfsreiche Makros
*
*
*
*/


#ifndef __XMEGA_MACROS_H__
#define __XMEGA_MACROS_H__


#define __XMEGA__
//#define __MEGA__

#ifdef __XMEGA__

	#define _PIN_CNFG_OUTPUT_( _port , _pin )		( _port.DIRSET = 1<<_pin )
	#define	_PIN_CNFG_INPUT_( _port , _pin )		( _port.DIRCLR = 1<<_pin )

	#define _PORT_CNFG_OUTPUT_( _port )				( _port.DIR = 0xFF )
	#define _PORT_CNFG_INPUT_( _port )				( _port.DIR = 0x00 )

	#define _PIN_SET_HIGH_( _port , _pin )			( _port.OUTSET = 1<<_pin )
	#define _PIN_SET_LOW_( _port , _pin )			( _port.OUTCLR = 1<<_pin )
	#define _PIN_TGL_( _port , _pin )				( _port.OUTTGL = 1<<_pin )

	#define _PORT_SET_HIGH_( _port )				( _port.OUT = 0xFF )
	#define _PORT_SET_LOW_( _port )					( _port.OUT = 0x00 )
	#define _PORT_TGL_( _port )						( _port.OUTTGL = 0xFF )

	#define _GET_PIN_STATE_( _port , _pin )			( _port.IN & 1<<_pin )

#elif __MEGA__
	
	#define _PIN_CNFG_OUTPUT_( _port , _pin )		( _port |= 1<<_pin )
	#define	_PIN_CNFG_INPUT_( _port , _pin )		( _port &= ~(1<<_pin) )

	#define _PORT_CNFG_OUTPUT_( _port )				( _port = 0xFF )
	#define _PORT_CNFG_INPUT_( _port )				( _port = 0x00 )

	#define _PIN_SET_HIGH_( _port , _pin )			( _port |= 1<<_pin )
	#define _PIN_SET_LOW_( _port , _pin )			( _port &= ~(1<<_pin) )
	#define _PIN_TGL_( _port , _pin )				( _port ^= 1<<_pin )

	#define _PORT_SET_HIGH_( _port )				( _port = 0xFF )
	#define _PORT_SET_LOW_( _port )					( _port = 0x00 )
	#define _PORT_TGL_( _port )						( _port ^= 0xFF )

	#define _GET_PIN_STATE_( _oin , _pin )			( _port & 1<<_pin )
	
#else
	#warning <Es wurde kein Prozessor ausgewaehlt..!>
#endif 

/*
*	Allgemeines
*/
#define _CALC_ARRAY_SIZE_( _array )				( sizeof( _array ) / sizeof( *_array ) )

#endif