/* Generated by CodeDescriptor 1.3.0.0714 */
/*
* Project Name      -> STS3x
* Version           -> 1.0.0.0810
* Author            -> Hm @ Workstadion.: QP-01-02
* Build Date        -> 10.08.2017 06:51:39
* Description       -> Description
*
*
*
*/


#ifndef STS3x_H_
#define STS3x_H_

#define STS3x_ADDR	( 0x4A << 1 )

#define STS3x_05_MPS_MSB			0x20
#define STS3x_05_MPS_HIG_LSB		0x32
#define STS3x_05_MPS_MED_LSB		0x24
#define STS3x_05_MPS_LOW_LSB		0x2F

#define STS3x_1_MPS_MSB				0x21
#define STS3x_1_MPS_HIG_LSB			0x30
#define STS3x_1_MPS_MED_LSB			0x26
#define STS3x_1_MPS_LOW_LSB			0x2D

#define STS3x_2_MPS_MSB				0x22
#define STS3x_2_MPS_HIG_LSB			0x36
#define STS3x_2_MPS_MED_LSB			0x20
#define STS3x_2_MPS_LOW_LSB			0x2B

#define STS3x_4_MPS_MSB				0x23
#define STS3x_4_MPS_HIG_LSB			0x34
#define STS3x_4_MPS_MED_LSB			0x22
#define STS3x_4_MPS_LOW_LSB			0x29

#define STS3x_10_MPS_MSB			0x27
#define STS3x_10_MPS_HIG_LSB		0x37
#define STS3x_10_MPS_MED_LSB		0x21
#define STS3x_10_MPS_LOW_LSB		0x2A

#define STS3x_FETCH_DATA_MSB		0xE0
#define STS3x_FETCH_DATA_LSB		0x00

#define STS3x_BREAK_COM_MSB			0x30
#define STS3x_BREAK_COM_LSB			0x93

#define STS3x_SOFT_RESET_MSB		0x30
#define STS3x_SOFT_RESET_LSB		0xA2

#define STS3x_HEATER_ENABLE_MSB		0x30
#define STS3x_HEATER_ENABLE_LSB		0x6D

#define STS3x_HEATER_DISABLE_MSB	0x30
#define STS3x_HEATER_DISABLE_LSB	0x66

#define STS3x_STATUS_REGISTER_MSB	0xF3
#define STS3x_STATUS_REGISTER_LSB	0x2D

enum sts3xState
{
	STS3X_NO_NEW_DATA = 1<<0,
	STS3X_CRC_ERR	  = 1<<1,	
};

enum sts3xBytes
{
	STS3X_MSB,
	STS3X_LSB,
	STS3X_CRC,
	
	STS3X_NUM_OF_BYTES,	
};

typedef struct  
{
	/*
	*	Status Bits ( enum sts3xState )
	*/
	uint8_t state;
	
	/*
	*	Niedrigst gemessene Temperatur
	*/
	int8_t lowest;
	
	/*
	*	Aktuell gemessene Temperatur
	*/
	int8_t actual;
	
	/*
	*	Höchst gemessene Temperatur
	*/
	int8_t highest;
	
}sts3x_t;

extern sts3x_t sts3x;

/* sts3xInit
* @para             -> -none
* @return           -> -none
* @description      -> please read the init
*/
void sts3xInit(void);

/* sts3xCalc
* @para             -> temp = temp AD - Value
* @return           -> temp in °C
* @description      -> -none
*/
int16_t sts3xCalc(uint16_t temp);

/* sts3xRead
* @para             -> -none
* @return           -> -AD Value
* @description      -> -none
*/
uint16_t sts3xRead(void);


/* sts3xGetTemp
* @para             -> -none
* @return           -> - Temperature in °C
* @description      -> -none
*/
int16_t sts3xGetTemp(void);

#endif