/* Generated by CodeDescriptor 1.5.0.0907 */
/*
* Project Name      -> stringHandler
* Version           -> 1.0.1.1124
* Author            -> Hm @ Workstadion.: QP-01-02
* Build Date        -> 20.09.2017 07:50:01
* Description       -> Description
*
*
*
*/

#include <avr/io.h>
#include <string.h>
#include <stdlib.h>

#include "cmd.h"

int8_t srchCmd(char *inBuff, char *srchCmd, uint8_t rawData)
{
	/*
	*	Zeiger auf den Beginn unserem Kommando (fals vorhanden!).
	*/
	char *cmdBeginnPtr    = NULL;
	
	/*
	*	Bestimmt die Länge unseres zweiten Parameters (srchCmd).
	*	Damit wir später unseren "gefundenen" Kommando String terminieren können.
	*/
	uint8_t srchCmdStrLen = strlen(srchCmd)+rawData;
	
	/*
	*	Zählt (falls vorhanden..) die Nutzdaten die Empfangen werden sollen.
	*	Damit wir diese später verarbeiten können.
	*/
	uint8_t rawDataBytes  = 0;
	
	/*
	*	Wurde als Parameter ein "NULL" Zeiger übergeben,
	*	so beenden wir die Funktion vorzeitig.
	*/
	if (inBuff == NULL || srchCmd == NULL)
	return -1;
 
         
	/*
	*    Aktuelles Kommando was gesucht wird, erst einmal zwischen speichern
	*	 damit wir später genau diesen Puffer bearbeiten können.
	*/
	char cmdBuff[26] = "";
	strcpy(cmdBuff,srchCmd);

	/*
	*   Wenn wir Nutzdaten empfangen haben, terminieren wir den String 
	*	nach dem letzten für uns relevanten Datenbyte.
	*/ 
	if (rawDataBytes > 0)cmdBuff[srchCmdStrLen-rawDataBytes] = '\0'; 

	/*
	*	Suchen wir nun nach unserem Kommando in unserem Empfangspuffer (inBuff)..
	*	Hierzu wird der String der aktuell als Parameter "srchCmd"
	*	übergeben wurde im Empfangspuffer (inBuff) gesucht.
	*
	*/      
	cmdBeginnPtr = strstr(inBuff,cmdBuff);
	if(cmdBeginnPtr == NULL)
	return -1;
	  
	/*
	*    Zum Schluss, terminieren wir noch das Ende von unserem Kommandopuffer.
	*	 Damit bezwecken wir das die nachfolgenden Zeichen abgeschnittenc
	*	 und nicht weiter mit verarbeitet werden.
	*/
	cmdBeginnPtr[srchCmdStrLen] = '\0';
 
	/*
	*	Haben wir unsern Kommando String gefunden, speicheren wir diesen in
	*   unserem Eingangs(Empfangspuffer(inBuff) Puffer ab damit wir diesen
	*	später evtl. noch weiterverarbeiten können.
	*
	*	Sollte kein Kommdo mit "srchCmd" übereinstimmen, wird der Eingangspuffer(inBuff)
	*	unbearbeitet zurück gelassen.
	*
	*/
	strcpy(inBuff,cmdBeginnPtr);
     
	return 0;
}

int8_t cmpCmd(char *strOne, char *strTwo)
{
	uint8_t strLenOne = strlen(strOne);
	uint8_t strLenTwo = strlen(strTwo);
	
	if (strLenOne != strLenTwo)
	return -1;
	
	if(strcmp(strOne,strTwo) == 0)
	return 0;
	else
	return -2;

	return -3;
}

uint8_t removeChar(char *str, uint8_t wanted)
{
    char * p = NULL;
	static uint8_t removed = 0;
	
    while (*str)
    {
        while (*str == wanted)
        {
			removed++;
            for (p = str; *p; p++)
            {
                *p = *(p + 1);
            }
        }
        str++;
    }
	return removed;
}


cmd_t cmd =
{
	.Search		= srchCmd,
	.Compare	= cmpCmd,
	.RemoveChar = removeChar,
};