/* Generated by CodeDescriptor 1.5.0.0907 */
/*
* Project Name      -> stringHandler
* Version           -> 1.0.1.1124
* Author            -> Hm @ Workstadion.: QP-01-02
* Build Date        -> 20.09.2017 07:50:01
* Description       -> Description
*
*
*
*/

#ifndef CMD_H
#define CMD_H

#include <avr/io.h>

typedef int8_t (*srchCmdPtr)(char *, char *, uint8_t);
int8_t srchCmd(char *inBuff, char *srchCmd, uint8_t rawBytes);

typedef int8_t (*cmpCmdPtr)(char *, char *);
int8_t cmpCmd(char *strOne, char *strTwo);

typedef struct{
	
	cmpCmdPtr			Compare;
	srchCmdPtr			Search;
}cmd_t;

extern cmd_t cmd;

#endif