/* Generated by CodeDescriptor 1.5.0.0907 */
/*
* Project Name      -> stringHandler
* Version           -> 1.0.1.1124
* Author            -> Hm @ Workstadion.: QP-01-02
* Build Date        -> 20.09.2017 07:50:01
* Description       -> Description
*
*
*
*/

#ifndef __CMD_H__
#define __CMD_H__

#include <avr/io.h>


typedef struct
{
	char	name[20];
	char	instruction[5];
	void*	(*fnc) (void* , void*);
}cmd_struct;



typedef int8_t ( *srchCmdPtr )( char * , char * , uint8_t );
int8_t srchCmd( char *inBuff , char *srchCmd , uint8_t rawBytes );

typedef int8_t ( *cmpCmdPtr )( char * , char * );
int8_t cmpCmd( char *strOne , char *strTwo );

typedef uint8_t ( *removeCharPtr )( char *str , uint8_t wanted );
uint8_t removeChar( char *str , uint8_t wanted );

typedef struct
{
	cmpCmdPtr			compare;
	srchCmdPtr			search;
	removeCharPtr		removeChar;
}cmd_t;

extern cmd_t cmd;

#endif